name: tests
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

env:
  ONEGP_TESTKIT_AUTH_URL: ${{secrets.ONEGP_TESTKIT_AUTH_URL}}

jobs:
  unit-tests:
    uses: salesforcecli/github-workflows/.github/workflows/unitTest.yml@main
  nuts:
    needs: unit-tests
    uses: salesforcecli/github-workflows/.github/workflows/nut.yml@main
    secrets: inherit
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false
    with:
      os: ${{ matrix.os }}
